/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import beans.AluguelBeans;
import persistencia.DataDAO;
import persistencia.VeiculoListaDAO;

import java.text.ParseException;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import persistencia.AluguelDAO;
import static telas.AluguelVeiculos.DataAtual;
import util.Conexao;

/**
 *
 * @author Eduar
 */
public class AluguelVeiculos extends javax.swing.JInternalFrame {

    /**
     * Creates new form AluguelVeiculos
     */
    public AluguelVeiculos()  {
        initComponents();
        DataAtual();
  
     
    }
    public void IniciarLista() throws Exception{
        VeiculoListaDAO Todosveiculos = new VeiculoListaDAO();
        try {
            VeiculoListaDAO veiculos = new VeiculoListaDAO();
            veiculos.ListarAllVeiculos();
            veiculos.ListarAllClientes();
        } catch (Exception ex) {
            Logger.getLogger(AluguelVeiculos.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }
    
    
    private static AluguelVeiculos instancia = null;

    public static AluguelVeiculos getInstancia() {
        if (instancia == null) {
            instancia = new AluguelVeiculos();
        }

        return instancia;
    }
    //
    

    //Horas

    public  static void  DataAtual(){
         Date dataAtual = new Date();
         Locale brasil = new  Locale("pt","BR");
        SimpleDateFormat dateFormat = new SimpleDateFormat("y-MM-dd", brasil);
        String dataFormatada = dateFormat.format(dataAtual);
        AluguelVeiculos.txtDataAluguel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT, brasil))));
        AluguelVeiculos.txtDataAluguel.setText(dataFormatada);
        
        
        //Calcular Calendario
        
        Calendar calendario = Calendar.getInstance();
        calendario.setTime(dataAtual);
        calendario.add(Calendar.MONTH,1);
        Date dataEntrega = calendario.getTime();
        String DataEntregar = dateFormat.format(dataEntrega);
        AluguelVeiculos.txtDataEntregar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        
        AluguelVeiculos.txtDataEntregar.setText(DataEntregar);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        VeiculoLista = new javax.swing.JComboBox<>();
        txtDataAluguel = new javax.swing.JFormattedTextField();
        txtDataEntregar = new javax.swing.JFormattedTextField();
        EntregueSim = new javax.swing.JRadioButton();
        EntregueNao = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        txtCliente = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        txtStatus = new javax.swing.JLabel();

        setClosable(true);
        setTitle("AutoLinkUp");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Alugar Veiculo"));

        jLabel2.setText("Veiculo:");

        jLabel3.setText("Data do Aluguel:");

        jLabel4.setText("Data da Entrega");

        jLabel5.setText("Cliente");

        jLabel6.setText("Entregue:");

        jLabel7.setText("Total:");

        jLabel8.setText("Observação");

        VeiculoLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeiculoListaActionPerformed(evt);
            }
        });

        txtDataAluguel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yy"))));
        txtDataAluguel.setActionCommand("<Not Set>");
        txtDataAluguel.setEnabled(false);
        txtDataAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataAluguelActionPerformed(evt);
            }
        });

        txtDataEntregar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yy"))));
        txtDataEntregar.setActionCommand("<Not Set>");
        txtDataEntregar.setEnabled(false);

        EntregueSim.setText("Sim");
        EntregueSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntregueSimActionPerformed(evt);
            }
        });

        EntregueNao.setSelected(true);
        EntregueNao.setText("Não");
        EntregueNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntregueNaoActionPerformed(evt);
            }
        });

        txtObservacao.setColumns(20);
        txtObservacao.setRows(5);
        jScrollPane1.setViewportView(txtObservacao);

        jButton1.setText("Alugar Veiculo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataAluguel)
                            .addComponent(txtDataEntregar)
                            .addComponent(jScrollPane1)
                            .addComponent(txtTotal)
                            .addComponent(txtCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EntregueSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EntregueNao)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(VeiculoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addGap(13, 13, 13))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(VeiculoLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDataAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDataEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(EntregueSim)
                    .addComponent(EntregueNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        txtStatus.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStatus)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntregueNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntregueNaoActionPerformed

        if(EntregueNao.isSelected() ){
                EntregueSim.setSelected(false);
        }
   
        
        
    }//GEN-LAST:event_EntregueNaoActionPerformed

    private void EntregueSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntregueSimActionPerformed
 
        if(EntregueSim.isSelected()){
            EntregueNao.setSelected(false);
        }
         
    }//GEN-LAST:event_EntregueSimActionPerformed
public static int EntregueVolue  ;
public static boolean StatusVeiculo;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Verificar se os campos estão vazio
        
        if (VeiculoLista == null || txtDataAluguel == null || txtDataEntregar == null || txtCliente == null || txtTotal == null || txtObservacao == null) {
            AluguelVeiculos.txtStatus.setText("Prenchar todos os campos");
        } else {
            //Pegar todas informações do campo e adicionar em uma variavel
            int id = 1;
            String observacao = txtObservacao.getText();
            String VeiculoClientes = VeiculoLista.getSelectedItem().toString();
            String AluguelCliente = txtCliente.getSelectedItem().toString();
            //Verificar status da entregar
            if (EntregueSim.isSelected()) {
                StatusVeiculo = true;
            } else {
                StatusVeiculo = false;
            }
            String DataClienteAluguel = txtDataAluguel.getText();
            String DataClienteEntregar = txtDataEntregar.getText();
            BigDecimal ValorReals = new BigDecimal(txtTotal.getText());
            String ValorNews = ValorReals.toString();
            
            //Alugar veiculo
            try {
                String DateStr = txtDataAluguel.getText();
                AluguelBeans ReservarVeiculo = new AluguelBeans();
                ReservarVeiculo.setDataAluguel(ReservarVeiculo.getDataAluguel());
                ReservarVeiculo.setDataEntrega(ReservarVeiculo.getDataEntrega());
                ReservarVeiculo.setCliente(ReservarVeiculo.getCliente());
                ReservarVeiculo.setObservacao(ReservarVeiculo.getObservacao());
                ReservarVeiculo.setValorPago(ReservarVeiculo.getValorPago());
                AluguelDAO alugueldeveiculos = new AluguelDAO();
                alugueldeveiculos.inserirVeiculo(ReservarVeiculo);
            } catch (Exception e) {
                
                JOptionPane.showMessageDialog(null, e + "", "Erro ao Alugar um veículo", JOptionPane.INFORMATION_MESSAGE);

            }

            //Verificar se foi inserido o aluguel
            if(AluguelDAO.Aluguelinserido == true){
               txtStatus.setText(" Aluguel inserido com sucesso!");
               txtCliente.setSelectedItem(0);
               VeiculoLista.setSelectedItem(0);
               txtTotal.setText("");
               txtObservacao.setText("");
            } else{
               txtStatus.setText(" Falha ao inserir o aluguel.");
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDataAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataAluguelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataAluguelActionPerformed

    private void VeiculoListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeiculoListaActionPerformed

    }//GEN-LAST:event_VeiculoListaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            VeiculoLista.removeAllItems();
            txtCliente.removeAllItems();
            IniciarLista();
        } catch (Exception ex) {
            Logger.getLogger(AluguelVeiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JRadioButton EntregueNao;
    public static javax.swing.JRadioButton EntregueSim;
    public static javax.swing.JComboBox<String> VeiculoLista;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JComboBox<String> txtCliente;
    public static javax.swing.JFormattedTextField txtDataAluguel;
    public static javax.swing.JFormattedTextField txtDataEntregar;
    public static javax.swing.JTextArea txtObservacao;
    public static javax.swing.JLabel txtStatus;
    public static javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}

