/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import beans.ClienteBeans;
//import static telas.Painel.txtinfor;
//import telas.Painel;
import javax.swing.JComboBox;
import javax.swing.JTextPane;
import javax.swing.JLabel;
import util.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import persistencia.ClienteDAO;

public class CadastrarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarCliente
     */
    public CadastrarCliente() {
        initComponents();
    }
    private static CadastrarCliente instancia = null;

    public static CadastrarCliente getInstancia() {
        if (instancia == null) {
            instancia = new CadastrarCliente();
        }

        return instancia;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jPanel1 = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          jLabel6 = new javax.swing.JLabel();
          txtNome = new javax.swing.JTextField();
          txtCpf = new javax.swing.JTextField();
          txtEmail = new javax.swing.JTextField();
          txtTelefone = new javax.swing.JTextField();
          txtEndereco = new javax.swing.JTextField();
          jButton1 = new javax.swing.JButton();
          txtStatus = new javax.swing.JLabel();
          txtUf = new javax.swing.JComboBox<>();

          setClosable(true);
          setResizable(true);
          setTitle("AutoLinkUp");
          setToolTipText("");

          jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Cliente"));

          jLabel1.setText("Nome");

          jLabel2.setText("CPF");

          jLabel3.setText("Email");

          jLabel4.setText("Telefone:");

          jLabel5.setText("Endereço");

          jLabel6.setText("UF");

          jButton1.setText("Cadastrar Cliente");
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });

          txtStatus.setText("Status");

          txtUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(jLabel1)
                                   .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                              .addGap(27, 27, 27)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(txtNome)
                                   .addComponent(txtCpf)
                                   .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                              .addGap(18, 18, 18)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel5)
                                   .addComponent(jLabel4)
                                   .addComponent(jLabel6))
                              .addGap(65, 65, 65)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(txtUf, 0, 169, Short.MAX_VALUE)
                                   .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(txtTelefone, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGap(25, 25, 25))
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtStatus)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(14, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(jLabel4)
                         .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel2)
                         .addComponent(jLabel5)
                         .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(jLabel6)
                         .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(31, 31, 31)
                    .addComponent(jButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txtStatus))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 //Atribuir os valores para as variavels
 String nome = txtNome.getText();
 String cpf = txtCpf.getText();
 String email = txtEmail.getText();
 String telefone = txtTelefone.getText();
 String endereco = txtEndereco.getText();
 String uf = txtUf.getSelectedItem().toString();
        //verificar se todos os campos foi prenchido
        if (nome.isEmpty() || cpf.isEmpty() || email.isEmpty() || telefone.isEmpty() || telefone.isEmpty() || endereco.isEmpty() || uf.isEmpty()) {
            txtStatus.setText(" Prenchar todos os campos");
        } else {
                try {
                    ClienteBeans clientes = new ClienteBeans(nome, endereco, uf, telefone, cpf, email);
                    ClienteDAO c1 = new ClienteDAO();
                    //Enviar as informações para o ClienteBeans
                    clientes.setNome(nome);
                    clientes.setCpf(cpf);
                    clientes.setEmail(email);
                    clientes.setTelefone(telefone);
                    clientes.setEndereco(endereco);
                    clientes.setUf(uf);
                    //Inserir usuario
                    int panel = JOptionPane.showConfirmDialog(null, "Você tem certeza de que deseja inserir este usuário?", "Aviso!", JOptionPane.OK_CANCEL_OPTION);
                    if (panel == 0) {
                        // Apagar as informações
                        txtCpf.setText("");
                        txtEmail.setText("");
                        txtEndereco.setText("");
                        txtTelefone.setText("");
                        txtUf.getSelectedItem().toString();
                        txtNome.setText("");
                        c1.Inserirdados(clientes);
                    } else {
                        JOptionPane.showMessageDialog(null, "Operação cancelada com êxito.", "Operação cancelada!", JOptionPane.OK_OPTION);
                    }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e + " ", "Operação falhou.", JOptionPane.INFORMATION_MESSAGE);
                txtStatus.setText(" Falha ao inserir o cliente.");
            }
       }  
    }//GEN-LAST:event_jButton1ActionPerformed


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton jButton1;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JPanel jPanel1;
     public static javax.swing.JTextField txtCpf;
     public static javax.swing.JTextField txtEmail;
     public static javax.swing.JTextField txtEndereco;
     public static javax.swing.JTextField txtNome;
     public static javax.swing.JLabel txtStatus;
     public static javax.swing.JTextField txtTelefone;
     public static javax.swing.JComboBox<String> txtUf;
     // End of variables declaration//GEN-END:variables
}
