/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import beans.VeiculoBeans;
import javax.swing.JOptionPane;
import persistencia.VeiculoListaDAO;
import persistencia.VeiculosDAO;

/**
 *
 * @author Eduar
 */
public class CadastrarVeiculo extends javax.swing.JInternalFrame {

    private static CadastrarVeiculo instancia = null;
    public static CadastrarVeiculo getInstancia() {
        if (instancia == null) {
            instancia = new CadastrarVeiculo();
        }

        return instancia;
    }
    public CadastrarVeiculo() {
        initComponents();
        try {
            IniciarLista();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
     
    }

   public void IniciarLista() throws Exception{
      VeiculoListaDAO veiculoListas = new VeiculoListaDAO();
       veiculoListas.ListarAcessorios();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroVeiculo = new javax.swing.JTextField();
        txtPlacaVeiculo = new javax.swing.JTextField();
        txtFabricante = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtPortas = new javax.swing.JTextField();
        txtAcessorios = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txtSatus = new javax.swing.JLabel();

        setClosable(true);
        setTitle("AutoLinkUp");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Veiculo"));

        jLabel1.setText("Número do Veiculo:");

        jLabel2.setText("Placa do Veiculo:");

        jLabel3.setText("Fabricante:");

        jLabel4.setText("Modelo:");

        jLabel5.setText("Ano do Modelo:");

        jLabel6.setText("Número de Portas:");

        jLabel7.setText("Acessorios:");

        txtAno.setToolTipText("");
        txtAno.setActionCommand("<Not Set>");
        txtAno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jButton1.setText("Cadastrar Veiculo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtSatus.setText("Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPlacaVeiculo)
                            .addComponent(txtNumeroVeiculo)
                            .addComponent(txtFabricante)
                            .addComponent(txtModelo)
                            .addComponent(txtAno, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtPortas)
                            .addComponent(txtAcessorios, 0, 222, Short.MAX_VALUE))
                        .addGap(32, 70, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSatus)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPortas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAcessorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(txtSatus)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String numero = txtNumeroVeiculo.getText();
       String placa = txtPlacaVeiculo.getText();
       String fabricante = txtFabricante.getText();
       String modelo = txtModelo.getText();
       String ano =txtAno.getText();
        int anocarro = 0;
        int totalportas = 0;
       String portas = txtPortas.getText();
       String acessorios = txtAcessorios.getSelectedItem().toString();
    
       
    //Converter Total de portas e ano do carro em Int
        try {
            totalportas = Integer.parseInt(portas);
            anocarro = Integer.parseInt(ano);
        } catch (NumberFormatException ex) {
            txtSatus.setText("Erro ao converter informações.");
        }
        //Verificar se os campos estão vazios
        if (numero.isEmpty() || placa.isEmpty() || fabricante.isEmpty() || modelo.isEmpty() || ano.isEmpty() || portas.isEmpty() || acessorios.isEmpty()) {
            CadastrarVeiculo.txtSatus.setText("Prenchar todos os campos");
            
        } 
        //Se todos os campos estiverem ok
        else {
            try {
                VeiculoBeans veiculos = new VeiculoBeans(numero, placa, fabricante, modelo, anocarro, totalportas, acessorios);
                VeiculosDAO addveiculo = new VeiculosDAO();
                veiculos.setNumero(numero);
                veiculos.setPlaca(placa);
                veiculos.setFabrica(fabricante);
                veiculos.setModelo(modelo);
                veiculos.setAnoModelo(anocarro);
                veiculos.setQtdPortas(totalportas);
                addveiculo.inserirveiculo(veiculos);
                txtSatus.setText(veiculos.getModelo() + " Foi adicionado com sucesso");
                // Limpar Campos
                CadastrarVeiculo.txtNumeroVeiculo.setText("");
                CadastrarVeiculo.txtPlacaVeiculo.setText("");
                CadastrarVeiculo.txtFabricante.setText("");
                CadastrarVeiculo.txtModelo.setText("");
                CadastrarVeiculo.txtPortas.setText("");
                CadastrarVeiculo.txtAcessorios.setSelectedItem(0);
                CadastrarVeiculo.txtAno.setText("");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Houve um erro ao inserir um veiculo", "Erro", JOptionPane.INFORMATION_MESSAGE);
                txtSatus.setText(" Falhar ao inserir Veículo");
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JComboBox<String> txtAcessorios;
    public static javax.swing.JTextField txtAno;
    public static javax.swing.JTextField txtFabricante;
    public static javax.swing.JTextField txtModelo;
    public static javax.swing.JTextField txtNumeroVeiculo;
    public static javax.swing.JTextField txtPlacaVeiculo;
    public static javax.swing.JTextField txtPortas;
    public static javax.swing.JLabel txtSatus;
    // End of variables declaration//GEN-END:variables
}
