
package telas;
import util.Conexao;

import beans.ClienteBeans;
import persistencia.LoginDAO;
import java.util.Scanner;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
/**
 *
 * @author Eduar 
 */
public class Programa extends javax.swing.JFrame {

    /**
     * Creates new form Programa
     */
    public Programa()   {
        initComponents();
        
        
       Timer timer = new Timer(4000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                LoginDAO.verificarconexao();
            }
        });

        // Inicie o timer
        timer.start();
        
   
    }
    /**
    public static void verificarconexao( ) throws SQLException{
  
        Conexao conexao = new Conexao();
       Connection conexaos= null;
        while(conexao != null){
                if(conexao != null){
                    conexaos.rollback();
                   menucliente.setEnabled(false);
                   menuveiculo.setEnabled(false);
                   
               } else{
                   menucliente.setEnabled(true);
                   menuveiculo.setEnabled(true);
                   break;
               }
            
        }
        
        
    }
    */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        PainelDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        iniciarsection = new javax.swing.JMenuItem();
        finalizarcount = new javax.swing.JMenuItem();
        menucliente = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuveiculo = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menualuguel = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        menufaturamento = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        VeiculosComAtrasos = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        ListaVeiculosAlugados = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AutoLinkUp");

        javax.swing.GroupLayout PainelDesktopLayout = new javax.swing.GroupLayout(PainelDesktop);
        PainelDesktop.setLayout(PainelDesktopLayout);
        PainelDesktopLayout.setHorizontalGroup(
            PainelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
        PainelDesktopLayout.setVerticalGroup(
            PainelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        jMenuBar1.setToolTipText("");
        jMenuBar1.setDoubleBuffered(true);
        LoginDAO.verificarconexao();

        jMenu1.setText("Sessão");

        iniciarsection.setText("Iniciar sessão");
        iniciarsection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbriTelaLogin(evt);
            }
        });
        jMenu1.add(iniciarsection);

        finalizarcount.setText("Encerrar conexão");
        finalizarcount.setEnabled(false);
        finalizarcount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarcountActionPerformed(evt);
            }
        });
        jMenu1.add(finalizarcount);

        jMenuBar1.add(jMenu1);

        menucliente.setText("Cliente");

        jMenuItem1.setText("Cadastrar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbriCadastrarCliente(evt);
            }
        });
        menucliente.add(jMenuItem1);

        jMenuItem2.setText("Pesquisar Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbriPesquisarCliente(evt);
            }
        });
        menucliente.add(jMenuItem2);

        jMenuBar1.add(menucliente);

        menuveiculo.setText("Veiculos");

        jMenuItem4.setText("Adicionar Veiculo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbriVeiculoAlugar(evt);
            }
        });
        menuveiculo.add(jMenuItem4);

        jMenuItem6.setText("Pesquisar Veiculo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuveiculo.add(jMenuItem6);

        jMenuBar1.add(menuveiculo);

        menualuguel.setText("Aluguel");

        jMenuItem5.setText("Alugar Veiculo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abriAluguelVeiculos(evt);
            }
        });
        menualuguel.add(jMenuItem5);

        jMenuItem8.setText("Pesquisar Aluguel");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abriPesquisarVeiculos(evt);
            }
        });
        menualuguel.add(jMenuItem8);

        jMenuBar1.add(menualuguel);

        menufaturamento.setText("Faturamento");

        jMenuItem10.setText("Consultar Faturamento");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menufaturamento.add(jMenuItem10);

        jMenuBar1.add(menufaturamento);

        VeiculosComAtrasos.setText("Veículos Atrasados");

        jMenuItem11.setText("Consultar Veiculos atrasados");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirTeladeVeiculosAtrasados(evt);
            }
        });
        VeiculosComAtrasos.add(jMenuItem11);

        jMenuBar1.add(VeiculosComAtrasos);

        ListaVeiculosAlugados.setText("Veiculos Alugados");

        jMenuItem12.setText("Todos Veículos Alugados");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listadealugueis(evt);
            }
        });
        ListaVeiculosAlugados.add(jMenuItem12);

        jMenuBar1.add(ListaVeiculosAlugados);

        jMenu2.setText("Informações do software");

        jMenuItem3.setText("Informação");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelDesktop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(PainelDesktop)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private CadastrarCliente cadastrar;
    
    private void AbriCadastrarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbriCadastrarCliente
        if (!CadastrarCliente.getInstancia().isVisible()) {
            PainelDesktop.add(CadastrarCliente.getInstancia());
            CadastrarCliente.getInstancia().setVisible(true);
        } else {
            CadastrarCliente.getInstancia().requestFocus();
        }
    }//GEN-LAST:event_AbriCadastrarCliente
  
    

    private void AbriPesquisarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbriPesquisarCliente
        if (!PesquisarCliente.getInstancia().isVisible()) {
            PainelDesktop.add(PesquisarCliente.getInstancia());
            PesquisarCliente.getInstancia().setVisible(true);
        } else {
            PesquisarCliente.getInstancia().requestFocus();
        }
        
        
        
    }//GEN-LAST:event_AbriPesquisarCliente


      private void AbriVeiculoAlugar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbriVeiculoAlugar
          if (!CadastrarVeiculo.getInstancia().isVisible()) {
              PainelDesktop.add(CadastrarVeiculo.getInstancia());
              CadastrarVeiculo.getInstancia().setVisible(true);
          } else {
              CadastrarVeiculo.getInstancia().requestFocus();
          }
      }//GEN-LAST:event_AbriVeiculoAlugar


      private void AbriTelaLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbriTelaLogin
             if (!TeladeLogin.getInstancia().isVisible()) {
              PainelDesktop.add(TeladeLogin.getInstancia());
              TeladeLogin.getInstancia().setVisible(true);
          } else {
              TeladeLogin.getInstancia().requestFocus();
          }

      }//GEN-LAST:event_AbriTelaLogin

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if (!PesquisarVeiculo.getInstancia().isVisible()) {
            PainelDesktop.add(PesquisarVeiculo.getInstancia());
            PesquisarVeiculo.getInstancia().setVisible(true);
        } else {
            PesquisarVeiculo.getInstancia().requestFocus();
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    private void finalizarcountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarcountActionPerformed
       LoginDAO.finalizarconexao();
        
            PainelDesktop.removeAll();
       
    }//GEN-LAST:event_finalizarcountActionPerformed

      private void abriAluguelVeiculos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abriAluguelVeiculos
         if (!AluguelVeiculos.getInstancia().isVisible()) {
            PainelDesktop.add(AluguelVeiculos.getInstancia());
            AluguelVeiculos.getInstancia().setVisible(true);
        } else {
            AluguelVeiculos.getInstancia().requestFocus();
        }
      }//GEN-LAST:event_abriAluguelVeiculos
  
    private void abriPesquisarVeiculos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abriPesquisarVeiculos
        if (!PesquisarAluguel.getInstancia().isVisible()) {
            PainelDesktop.add(PesquisarAluguel.getInstancia());
            PesquisarAluguel.getInstancia().setVisible(true);
        } else {
            PesquisarAluguel.getInstancia().requestFocus();
        }
    }//GEN-LAST:event_abriPesquisarVeiculos

      private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
             if (!TelaFaturamento.getInstancia().isVisible()) {
            PainelDesktop.add(TelaFaturamento.getInstancia());
            TelaFaturamento.getInstancia().setVisible(true);
        } else {
            TelaFaturamento.getInstancia().requestFocus();
        }
      }//GEN-LAST:event_jMenuItem10ActionPerformed

      private void AbrirTeladeVeiculosAtrasados(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirTeladeVeiculosAtrasados
          if (!VeiculosAtrasado.getInstancia().isVisible()) {
              PainelDesktop.add(VeiculosAtrasado.getInstancia());
              VeiculosAtrasado.getInstancia().setVisible(true);
          } else {
              VeiculosAtrasado.getInstancia().requestFocus();
          }
      }//GEN-LAST:event_AbrirTeladeVeiculosAtrasados
private ListadeAluguel veiculosalugados;
    private void Listadealugueis(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listadealugueis
             if (!ListadeAluguel.getInstancia().isVisible()) {
              PainelDesktop.add(ListadeAluguel.getInstancia());
              ListadeAluguel.getInstancia().setVisible(true);
          } else {
              ListadeAluguel.getInstancia().requestFocus();
          }
    }//GEN-LAST:event_Listadealugueis

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       if(!DialogInformar.getInstancia().isVisible()){
           PainelDesktop.add(DialogInformar.getInstancia());
           DialogInformar.getInstancia().setVisible(true);
       } else{
           DialogInformar.getInstancia().requestFocus();
       }
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                   
                    new Programa().setVisible(true);
            
                
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu ListaVeiculosAlugados;
    private javax.swing.JDesktopPane PainelDesktop;
    public static javax.swing.JMenu VeiculosComAtrasos;
    public static javax.swing.JMenuItem finalizarcount;
    public static javax.swing.JMenuItem iniciarsection;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    public static javax.swing.JMenu menualuguel;
    public static javax.swing.JMenu menucliente;
    public static javax.swing.JMenu menufaturamento;
    public static javax.swing.JMenu menuveiculo;
    // End of variables declaration//GEN-END:variables
}
